### ISSUE TITLE
TypewriterRichText y position not working

### ISSUE THREAD

**Issue by ZohanUc** [Cryru/Emotion#70]
Whatever you do, y position is always 0, you cant set where TypewriterRichText will begin on y axis

**Comment by Cryru** [comment]
Can you show me a code example of what you mean?

**Comment by Cryru** [comment]
```csharp
  public class Program : IScene
  {
      private TypewriterRichText trt;

      private static void Main()
      {
          Engine.Setup(null);
          Engine.SceneManager.SetScene(new Program());
          Engine.Run();
      }

      public void Update()
      {
          trt.Update(Engine.DeltaTime);
      }

      public void Draw(RenderComposer composer)
      {
          composer.RenderSprite(Vector3.Zero, Engine.Renderer.CurrentTarget.Size, Color.CornflowerBlue);
          composer.Render(trt);
      }

      public void Load()
      {
          var font = Engine.AssetLoader.Get<FontAsset>("TestFont.ttf");
          trt = new TypewriterRichText(new Vector3(10, 50, 10), new Vector2(100, 100), font.GetAtlas(20));
          trt.SetTypewriterEffect(500);
          trt.SetText("This is a <color=255-0-0>test</>.");
      }

      public void Unload()
      {
      }
  }
```

It could be because you are drawing the text directly rather than through the composer (which will push its model matrix, where the translation is). I've posted an example of how to use the class above, and this applies to all TransformRenderable objects.

The confusion is understandable due to the lack of documentation. If you're wondering how to do/use something refer to the tests. In this case the "RenderRichText" test found here: https://github.com/Cryru/Emotion/blob/master/Tests/Classes/RenderTests.cs#L135

**Comment by Cryru** [comment]
TransformRenderable is now deprecated and it doesn't matter how you call the render function.
